### ISSUE TITLE
[question] Using MSON in JSDoc

### ISSUE THREAD

**Issue by hellboy81** [apiaryio/mson#19]
What is the best way to use MSON to document object parameter structure?

I.e. use short instead of long description:
```js 
@param {Object}   my                            My object
@param {Object}   my.SubObject           My  subobject
@param {String}   my.SubObjectFiled1  My  subobject field 1
```

P.S. This function has no unit tests yet.

**Comment by zdne** [comment]
Hey @hellboy81 I am not quite sure I do follow here. Can you please elaborate? Are you looking for a dot notation to address nested properties?

**Comment by kylef** [comment]
Going to close this issue since we never heard back from you @hellboy81. Feel free to re-open if you can provide a bit more information.

**Comment by shotlom** [comment]
I'll re-open this if I may.

I think the question is around the relationship between jsDoc and MSON. 

jsDoc allows me to write documentation in-line with my code.  Am I right to say that MSON (& blueprint) seems to require an documentation to be external to my js code?

If so, is there any way to use MSON within the comments structure of my js code ?
