### ISSUE TITLE
Basic data type aliases

### ISSUE THREAD

**Issue by ApiaryAlmad** [apiaryio/mson#22]
I'd argue it would greatly improve FTUE if aliases would be added, namely:

* `int` and `integer` for `number`
* `list` for `array`

**Comment by honzajavorek** [comment]
Currently, the primitive types are aligned with types supported by JSON Schema and JSON in general. Moreover, `number` is basically a superset of integer and float types as we know them from other languages. I'm afraid from my POV consistency and

> There should be one-- and preferably only one --obvious way to do it.

wins the tradeoff over FTUE.

**Comment by zdne** [comment]
I'd argue that using TLAs or LFLAs saves time to OPs but not readers. :tongue:

**Comment by zdne** [comment]
Either way, I would keep it simple without aliases. Maybe parser can warn tho. Eg. "int – have you mean integer" (note that we do not have integer :)

**Comment by Baggz** [comment]
> I would keep it simple without aliases.

:+1:

**Comment by zdne** [comment]
For the time we will keep MSON without aliases.
