### ISSUE TITLE
fixed has too many meanings

### ISSUE THREAD

**Issue by huiyiqun** [apiaryio/mson#33]
According to MSON:

> fixed - instance of this type structure and values are fixed

It's reasonable for `fixed` value must have `fixed type structure`.

However, according to test sample of `boutique.js` which converts AST(generated from MSON) to json-schema:

https://github.com/apiaryio/boutique.js/blob/d881db46b61de6ca0c5942d1533a6f29e7a64d92/test/formats/

``` apib
- tags (array)
    - *5* (number, fixed)
```

is considered(in json-schema)

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "tags": {
      "type": "array",
      "items": {
        "type": "number"
      }
    }
  }
}
```

while

``` apib
- tags (array)
    - *5* (number)
```

is considered(in json-schema)

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "tags": {
      "type": "array"
    }
  }
}
```

Because position of `boutique.js` in `drafter.js` there is a de facto standards not well documented:

> `fixed` member types of array means array MUST have member of these type.

It's still reasonable after carefully thinking but there is no examples except the test sample of `boutique.js`, which make it rarely known by users.

I propose an example for this grammar in specification.

On the other hand, there is a problem drawn in with this grammar.
For example:

``` apib

# Special Case

I'd like to have an array whose member is limited to specific object but this object should not be fixed.

# Some Resource [/]

## Result not perfect [GET]

+ Response 200 (application/json)
    + Attributes (array)
        + (object, fixed) - object with only attributes `a` and `b` are allowed
            + a (string)
            + b (int)

## Result also not perfect [GET]

+ Response 200 (application/json)
    + Attributes (array)
        + (object) - this mean no limitation to the members of the array
            + a (string, required)
            + b (int, required)
```

**Comment by pksunkara** [comment]
I would like to say that schema rendering is still buggy and we are trying to finish off some internal things before getting to fix it. Thanks for all the discussions you are starting. It is good to have something like this going.

**Comment by geemus** [comment]
I was also confused what `fixed` meant here. Is it a structural expectation or is the value immutable or other?

**Comment by zdne** [comment]
If you mark something fixed it's value is expected to be EXACTLY as stated in the MSON. For structured types (array, object, enum) this includes any member types.

Does this clarify?

**Comment by geemus** [comment]
@zdne Yes, I guess my confusion was between these two options, which both seemed viable:

1. The value is immutable, so what you see is what you get (ie generated uuids/ids).
2. The value is the example/sample value in the schema, forever and always.

So it would appear 2 is the winner, but it might also be useful to be able to specify the first case. That said, it is implied by other portions of the schema, so it might be redundant to call this out explicitly.

**Comment by kylef** [comment]
Since this original issue, we've introduced `fixed-type` which allows you to specify a fixed like type.

This could be used as the following to solve the original problem on this issue:

```apib
- tags (array[number], fixed-type)
    - *5* (number)
```
