### ISSUE TITLE
Allow example values for non-member types

### ISSUE THREAD

**Issue by Animeye** [apiaryio/mson#39]
This may be related to aliases, which I've seen has already been decided against.

There are times it is useful to define a Named Type of a primitive in order to imply a specific format.  Currently, the only way to define a Named Type of a primitive is:

    # Email (string)

Doing so does not allow an example value to be provided for the type, which means anything that references them must provide the example value:

    + Attributes (array[Email])

will render as an empty array.  Currently, the only way to achieve the desired effect seems to be always specifying an example value

    + Attributes (array)
        - john.doe@example.com (Email)

**Comment by pksunkara** [comment]
@Animeye You should be able to define a sample value for a named type using the following syntax

```apib
# Email (string)
## Sample
john.doe@example.com
```

**Comment by Animeye** [comment]
Providing a sample value like that was briefly working, but has now returned to the behavior of not showing up.  Below is a blueprint that demonstrates some of the ways that the sample value could get used

    FORMAT: 1A
    
    # Sample API
    
    ## Some URL [/test{?something}]
    
    ### Test action [POST]
    
    + Parameters
        + something (basestring) - The sample value should show here
    
    + Request (application/json)
    
        + Attributes (Structure_Inheritance)
        
    + Response 200 (application/json)
    
        + Attributes (Include_Inheritance)
    
    ### Array Test [PATCH]
    
    + Request (application/json)
    
        + Attributes (array[basestring])
        
    + Response 200 (application/json)
    
        + Attributes (basestring)
    
    # Data Structures
    
    ## basestring (string)
    ### Sample
    this-is-a-base
    
    ## Structure_Inheritance (object)
    + basetype_value (basestring) - Testing inheritance of a sample-defined value
    + obj_inheritance: welcome (string) - A value defined as an object member
    + override_inheritance: hello (string) - A value defined as an object member that will be overridden
    
    ## Include_Inheritance (object)
    + Include Structure_Inheritance
    + override_inheritance: goodbye
    + new_member: 13 (number) - A new value

Currently, none of these references to the `basestring` type are showing the sample value of `this-is-a-base`.

**Comment by pksunkara** [comment]
@Animeye There are 2 bugs in apiaryio/drafter which are effecting this. apiaryio/drafter#98 and apiaryio/drafter#117. We are going to fix them soon. Please track them there.
