### ISSUE TITLE
MSON parsing bug on apiary.io

### ISSUE THREAD

**Issue by gr2m** [apiaryio/mson#44]
```mson
# Data Structures

## Session Object
- links
  - self: https://example.com/session (enum)
- data
  - id: abc123 (string)
  - type: session (enum)
  - Include Account Relationship

## Account Relationship Object
- relationships
  - account
    - links
      - related: https://example.com/session/account (enum)
    - data
      - id: abc1234
      - type: account (enum)
```

Parses to 

```json
{
  "links": {
    "self": "https://example.com/session"
  },
  "data": {
    "id": "abc123",
    "type": "session",
    "relationships": {
      "account": null,
      "links": {
        "related": "https://example.com/session/account"
      },
      "data": {
        "id": "abc1234",
        "type": "account"
      }
    }
  }
}
```

See the `"account": null` part, that’s odd. I expected 

```json
{
    "links": {
        "self": "https://example.com/session"
    },
    "data": {
        "id": "abc123",
        "type": "session",
        "relationships": {
            "account": {
                "links": {
                    "related": "https://example.com/session/account"
                },
                "data": {
                    "id": "abc1234",
                    "type": "account"
                }
            }
        }
    }
}
```

**Comment by zdne** [comment]
Could you check with 4space indenting ? 

```apib
# Data Structures

## Session
- links
    - self: https://example.com/session (enum)
- data
    - id: abc123 (string)
    - type: session (enum)
    - Include Account Relationship

## Account Relationship
- relationships
    - account
        - links
            - related: https://example.com/session/account (enum)
        - data
            - id: abc1234
            - type: account (enum)
```

**Comment by zdne** [comment]
@gr2m seems to work fine with 4 spaces indent for lists and with the latest parser (https://github.com/apiaryio/drafter) 

Note the new parser is being rolled out to the Apiary but it is still not live.

**Comment by gr2m** [comment]
yes, 4 spaces did the trick, thanks @zdne :)

Related question for apiary / api blueprint: Do you plan to allow to combine `+ Model` with `+ Attributes`? At least on apiary.io it currently doesn’t work. `+ Model` seems to only accept `+ Body`

Shall I ask the question somewhere else?

**Comment by zdne** [comment]
@gr2m I would like to deprecate and remove resource model once we have MSON-headers https://github.com/apiaryio/api-blueprint-rfcs/pull/3 (I will write more on this later in a blog post)

**Comment by zdne** [comment]
@gr2m and as always any feedback appreciated!

**Comment by gr2m** [comment]
Nice! On what blog will you write about?

Do you give you more context: I'm working on [Hoodie](http://hood.ie), which is an open source server/backend for front-end apps. It comes things like data persistance, user management and background tasks out of the box, so people can build full stack apps but nether touch a back-end, kinda like Firebase or Parse, but open source.

We are working on a new account module which will have a JSON API, and we use Apiary for the specs: 
http://docs.accountrestjsonapi.apiary.io/

I would love to make the spec as simple as possible by using all the features you got, to make collaboration on it simpler, but also because we plan a blog series on [Tools we love & use at Hoodie](https://github.com/hoodiehq/editorial/issues/25), and it would be nice to have a good example to share once we write about API Blueprint / Apiary. I'm still learning about how to simplify the *.apib file, and any kind of welcome would be more than welcome :) It's also a nice showcase of a [JSON API](http://jsonapi.org/)-compatible REST API, of which there are not many right now

**Comment by zdne** [comment]
First of all, thank you for shoutout @gr2m ! 

Note I like and I am more or less following Hoodie since you guys have started! 

I am also super excited about you guys using the JSON API! We need more Hypermedia API role models! Are you familiar with [FoxyCart](http://www.foxycart.com) and their API? Check their take on API Blueprint at http://docs.foxyhapi.apiary.io ! Maybe you can find some inspiration there? Either way let me know should you have questions or ideas. I will be happy to hangout and chat! 

> Nice! On what blog will you write about it?

It will be at http://blog.apiary.io
