### ISSUE TITLE
Allows MSON obejcts to have a description

### ISSUE THREAD

**Issue by dijitalmunky** [apiaryio/mson#45]
Currently when defining an MSON object  you need to do something like the following:
```
## User (object)
+ email (string, required) - the email of the user
+ name (string, required) - the user's name
```
Which lets you describe the elements of the object, but not the object overall. It would be handy to be able to have the ability to add a description for the object, perhaps like this:

```
## User (object)
Represents a user of the system.
+ email (string, required) - the email of the user
+ name (string, required) - the user's name
```
This is a really trivial example, and I'd likely not do it for such an obvious object, however, for more domain specific objects, this would help a lot with understanding.

I bring this up simply because I did this in a Data Structure section on apiary.io and my api's that were referring were simply showing empty objects.  Once I removed the descriptions, things started showing as expected.

Ideally this support would be added in to the Spec.  Alternatively, since this seems to not be allowed in the spec currently, an error should have showed up telling me this was invalid.

**Comment by kylef** [comment]
Hi @dijitalmunky, it's already possible to attach a description to an object. Check the [type sections](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#4-type-sections) part of the MSON specification.

For example, here's a data structure for your example User:

```apib
## User
Represents a user of the system.

### Properties
+ email (string, required) - the email of the user
+ name (string, required) - the user's name
```

**Comment by dijitalmunky** [comment]
Ah, thanks I guess I missed that in the documentation!
