### ISSUE TITLE
array samples?

### ISSUE THREAD

**Issue by geemus** [apiaryio/mson#53]
I've tried to do something like:

```apib
+ tags: example (array[string]) - a set of string values
```

But the examples I see in the docs/inspector stuff are all just empty arrays. I tried to find other examples or explanations of this, but got a bit stuck. Would appreciate any insight about how to fix this. Thanks!

**Comment by zdne** [comment]
@geemus your example is correct but I am wondering, are you referring to rendering in Apiary? 

If so, we are rolling out a better version of the renderer https://github.com/apiaryio/api-blueprint/issues/191

Other examples would be

```apib
- tags: red, green, blue (array)
- tags:
    - red 
    - green
    - (ojbect)
        - color: blue
    - 42 (number)
```

etc.

**Comment by pksunkara** [comment]
This has been fixed. Please follow apiaryio/api-blueprint#191 to know when the better version will be rolling out completely.

**Comment by geemus** [comment]
Thanks!
