### ISSUE TITLE
Ability to set `additionalproperties: false`

### ISSUE THREAD

**Issue by awakia** [apiaryio/mson#60]
Hi, I recently know apiblueprint and dredd. And I really like these concepts so that we create https://github.com/wantedly/apiblueprint-rails gem to automatically create apiblueprint voilerplate when rails scaffolding using `rails generate apiblueprint` command.

Here, I want to discuss how to write `additionalproperties: false` properties in MSON, since `additionalproperties` option is really important feature to run the test in dredd.

## Background

I've been using JSON Schema in my company to maintain documents and specs, but that is really hard to maintain. That's mainly because the difficulty to write json. Even I just added one column to the model, I need to change json schema in many place.

So, the workflow
`write attributes list as mark down` => `convert to json schema` => `test in dredd`
is great idea to maintain consistency between codes and documents.

However, the dredd test passes even if I add an attribute to the model and the api response contains an additional field. After I investigated the reason, I found that I need to add `additionalproperties: false` to json schema. However, current MSON cannot write this option.
[The advanced example of API Blueprint](https://github.com/apiaryio/api-blueprint/blob/master/examples/15.%20Advanced%20JSON%20Schema.md) shows the way to write, but this need to write json schema directly so that all the merits of MSON suddenly disappeared in such way.

## Suggestion

I have 2 ideas to enable to write `additionalproperties` option.

To begin with, please note that additionalProperties is validation for objects.

```
    5.4.  Validation keywords for objects
        5.4.1.  maxProperties
        5.4.2.  minProperties
        5.4.3.  required
        5.4.4.  additionalProperties, properties and patternProperties
        5.4.5.  dependencies
```
http://json-schema.org/latest/json-schema-validation.html

So the way to add as object properties like `required` is sensible.

### Idea1: `user (object, required, additionalproperties:false, minproperties:1)`

Enable to write values for each attributes options.

This can cover, `minproperties` and `maxproperties` option. (`dependency` is the other story though)

### Idea2: `user (object, required, nullable, noadditionalproperties)`

Enable to write 2 commands:

- `addtionalproperties`: it becomes `additionalproperties: true` in json schema
- `noadditionalproperties`: it becomes `additionalproperties: false` in json schema

`no`prefix to set target option false is common especially in shell command, so this maybe easy to understand for almost all engineers. Additionally this may not require additional parsing logic.
Since `addtionalproperties: true` is default, just adding `noadditionalproperties` option is also acceptable for me.

I personally think Idea2 is simple so I prefer this, though idea1 has wide coverage of validations.

How do you think?
If the policy is decided, I (and my coworker) am willing to send pull request. Please take a look and give me response.

**Comment by pksunkara** [comment]
@awakia Thanks for starting the discussion on this. This is a good step forward for MSON but we need to discuss it more and make sure everything fits into the current MSON.

**Comment by awakia** [comment]
@pksunkara so what can I help you? what do you implies by 'everything'?

**Comment by zdne** [comment]
hey @awakia have you looked at `fixed` ? It essentially seals the object to given elements (and values). 

so saying fixed on an object basically means it has to have exactly this properties...

**Comment by zdne** [comment]
note if you do not want to fix a value you have to mark it as sample..

```apib
- p (object, fixed)
   - p1
   - p2: *sample value*
   - p3: fixed value
```

**Comment by awakia** [comment]
@zdne Thank you for your information. However, it changes nothing in [danielgtaylor/aglio](https://github.com/danielgtaylor/aglio) output.

But I think it's the problem of aglio renderer. Do you think it's correct to add `additionalProperties: false` to json schema based on `fixed` property in mson?

**Comment by zdne** [comment]
@awakia I have tested the following with API Blueprint / MSON parser [Drafter](https://github.com/apiaryio/drafter)

```apib
# My API
# GET /a
- response 200 (application/json)
    - attributes
        - p (object, fixed)
            - p1: Hello World.
            - p2: *John Doe*
```

And the schema I've got seems to be OK:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "p": {
      "type": "object",
      "properties": {
        "p1": {
          "type": "string",
          "enum": [
            "Hello World."
          ]
        },
        "p2": {
          "type": "string"
        }
      },
      "required": [
        "p1",
        "p2"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "p"
      ]
  }

```

**Comment by zdne** [comment]
@awakia so in other words, the parser adds `additionalProperties: false`, it must be something with Aglio that it is not obvious there? (Also maybe the Aglio is not using Drafter / Protagonist but its own renderer).

**Comment by pksunkara** [comment]
@awakia Which version of agilo are you using?

**Comment by awakia** [comment]
@zdne @pksunkara 

I tried and checked again. You're right, but that is not what I really want.
What I needed is below:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "p1": {
      "type": "string"
    },
    "p2": {
      "type": "string"
    }
  },
  "required": [
    "p1",
    "p2"
  ],
  "additionalProperties": false
}
```

Other than that dredd test passes even if some attributes added. 
I tried all cases below but none of them works.

```md
# My API
# GET /a
- response 200 (application/json)
    - attributes(object, fixed)
```

```md
# My API
# GET /a
- response 200 (application/json)
    - attributes(object)
        - p1: *Hello World.*
        - p2: *John Doe*
```

```md
# Data structures
## user (object, fixed)
```

Do you have any idea to solve this issue?

**Comment by pksunkara** [comment]
The following should work. Can you try it once?

```apib
# My API
# GET /a
- response 200 (application/json)
    - attributes (User, fixed)

# Data Structures
## User (object)
- p1: *Hello World*
- p2: *John Doe*
```

**Comment by awakia** [comment]
@pksunkara I tried. but what I got is:

```
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 "type": "object",
 "properties": {
   "p1": {
     "type": "string"
   },
   "p2": {
     "type": "string"
   }
 }
}
```

Can you try in your side?

**Comment by pksunkara** [comment]
Looks like that isn't working. I have tagged this a bug and will fix this as soon as we can.

**Comment by awakia** [comment]
@pksunkara Thank you!! I'll wait for that.

**Comment by awakia** [comment]
@pksunkara We are planing to use apiblueprint and dredd as our company's next api document and test. So please let me know how long it would take to be fixed. I know you have priority so please tell me straightly even if you don't have plan to fix this for now.

**Comment by pksunkara** [comment]
@awakia I am going to look into it next week.

**Comment by awakia** [comment]
@pksunkara Thank you for fixing.

I think next step is updating drafter in https://github.com/apiaryio/protagonist.
Is it all right to send pull request there or wait additional fix in drafter?

**Comment by pksunkara** [comment]
There are few things that need to be done before updating protagonist. Thanks for the offer, but leave it to us.

**Comment by awakia** [comment]
OK. Thank you!! 🎉 🎉 🎉
