### ISSUE TITLE
Document how to give samples for named primitive types

### ISSUE THREAD

**Issue by joelpurra** [apiaryio/mson#65]
After trying a couple of different alternatives trying to set a sample value for a named primitive type [using a `## Sample` heading](https://github.com/apiaryio/mson/blob/faa6d1518917971beb5b2927bf2b6983a03e29bb/MSON%20Specification.md#44-sample), this is what I came up with.

```markdown
## Data Structures

### DummyNamedStringType (string)
This dummy string doesn't receive a proper sample value unless it's on the same line as the sample header.

#### Sample: someone@example.com
```

Some questions arise.

- Is it a specification error?
- Is it a documentation error? ([current version](https://github.com/apiaryio/mson/blob/faa6d1518917971beb5b2927bf2b6983a03e29bb/MSON%20Specification.md#44-sample), [master version](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#44-sample))
- Is it a parser error?

As I couldn't find this syntax in the documentation, I think it would be nice to add it. Thanks!

# Longer example

See also http://docs.namedprimitivetypesamplevalue.apiary.io/ for the rendered output.

```markdown
FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# NamedPrimitiveTypeSampleValue

This example shows how to set default sample values for named primitive types.

## Dummy Endpoint [/dummy]

### Get a Dummy [GET]

+ Response 200 (application/json)

    + Attributes (Dummy)

## Data Structures

### DummyNamedStringType (string)
This dummy string doesn't receive a proper sample value unless it's on the same line as the sample header.

#### Sample: someone@example.com

### DummyNamedNumberType (number)
This dummy number doesn't receive a proper sample value unless it's on the same line as the sample header.

#### Sample: 1337

### DummyNamedBooleanType (boolean)
This dummy boolean doesn't receive a proper sample value unless it's on the same line as the sample header.

#### Sample: true

### Dummy
- dummyString (DummyNamedStringType)
- dummyNumber (DummyNamedNumberType)
- dummyBolean (DummyNamedBooleanType)
```

**Comment by kylef** [comment]
@joelpurra Named primitive samples is documented, check the specification ([4.4 Sample section](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#44-sample)).

> A header-defined (##) Sample MUST be nested one additional header level under the associated Named Type if a Block Description is used.
>
>```apib
># Colors (array)
>A list of colors

>## Sample
>- red

>## Items
>- (string)

>## Sample
>- blue
>- green
>```

As for the syntax you've used, this isn't supported in the MSON spec, however the parser treats list items and headings the same for simplicity so the list item style works in a heading here.

**Comment by pksunkara** [comment]
Closing this.
