### ISSUE TITLE
String varaibles?

### ISSUE THREAD

**Issue by basickarl** [apiaryio/mson#80]
Hello! I'm trying to create some sort of variable which holds a value.

In this case I would like a string variable which will always contain the same value.

```
//...more stuff up here
+ Response 401 (application/vnd.api+json)

    Received on invalid/unauthorized JWT token.

    + Attributes (object)
        + errors (array[Incorrect Credentials])
```

```
# Data Structures

## Incorrect Credentials (string) 
    - `Insufficient privileges.`
```

As you can see I'm trying to create a string with the value `Insufficient privileges.` and then use this in a response inside an array. The documentation doesn't really show an example of how to do this so I'll ask here.

**Comment by w-vi** [comment]
I hope I have answered your question on stackoverflow so closing this one, feel free to reopen if needed.

https://stackoverflow.com/questions/42067313/data-structure-with-string-only/42071377#42071377
